

# Autogenerated! Do not edit!
send -- "caesar\r"

expect  "group name:"
send -- "Conundrum\r"

expect  "word:"
send -- "qwerty\r"

expect  "at:"
send -- "4\r"

expect  "> "
send -- "read\r"

expect  "> "
send -- "aaaaaaaaaa\r"

expect  "> "
send -- "c\r"

expect  "> "
send -- "back\r"

expect  "> "
send -- "read\r"

expect  "> "
send -- "bbbbbbbbbb\r"

expect  "> "
send -- "c\r"

expect  "> "
send -- "back\r"

expect  "> "
send -- "read\r"

expect  "> "
send -- "cccccccccc\r"

expect  "> "
send -- "c\r"

expect  "> "
send -- "back\r"

